* HELLO WORLD FOR THE IBM SYSTEM/360 (OS/360, MVS 3.8J, Z/OS).
* WTO HANDS THE MESSAGE TO THE SYSTEM, WHICH SHOWS IT ON THE
* OPERATOR CONSOLE AND IN THE JOB LOG. THE REST IS THE USUAL
* LINKAGE HOUSEKEEPING EVERY BATCH PROGRAM DOES.
HELLO    CSECT
         STM   14,12,12(13)        SAVE CALLER'S REGISTERS
         BALR  12,0                SET UP A BASE REGISTER
         USING *,12                TELL THE ASSEMBLER ABOUT IT
         WTO   'HELLO, WORLD!'     WRITE TO OPERATOR (SVC 35)
         LM    14,12,12(13)        RESTORE REGISTERS
         SR    15,15               RETURN CODE 0
         BR    14                  BACK TO THE SYSTEM
         END   HELLO
